package com.hibernate;

/**
 * RailwayTimetable generated by hbm2java
 */
public class RailwayTimetable implements java.io.Serializable {

	/*private RailwayTimetableId id;

	
	public RailwayTimetable() {
	}

	public RailwayTimetable(RailwayTimetableId id) {
		this.id = id;
	}

	public RailwayTimetableId getId() {
		return this.id;
	}

	public void setId(RailwayTimetableId id) {
		this.id = id;
	}*/
	
	private String TrainNo;
	private String StationCode;
	private String ArrivalTime;
	private String DepartureTime;
	private String DistanceCovered;
	private String Day;
	private String Route;
	
	
	public RailwayTimetable() {
	}

	public RailwayTimetable(String TrainNo, String StationCode,String ArrivalTime,String DepartureTime,String DistanceCovered,String Day,String Route) {
		this.TrainNo = TrainNo;
		this.StationCode = StationCode;
		this.ArrivalTime=ArrivalTime;
		this.DepartureTime=DepartureTime;
		this.DistanceCovered=DistanceCovered;
		this.Day=Day;
		this.Route=Route;		
	}
	
	public String getTrainNo() {
		return TrainNo;
	}
	public void setTrainNo(String trainNo) {
		TrainNo = trainNo;
	}
	public String getStationCode() {
		return StationCode;
	}
	public void setStationCode(String stationCode) {
		StationCode = stationCode;
	}
	public String getArrivalTime() {
		return ArrivalTime;
	}
	public void setArrivalTime(String arrivalTime) {
		ArrivalTime = arrivalTime;
	}
	public String getDepartureTime() {
		return DepartureTime;
	}
	public void setDepartureTime(String departureTime) {
		DepartureTime = departureTime;
	}
	public String getDistanceCovered() {
		return DistanceCovered;
	}
	public void setDistanceCovered(String distanceCovered) {
		DistanceCovered = distanceCovered;
	}
	public String getDay() {
		return Day;
	}
	public void setDay(String day) {
		Day = day;
	}
	public String getRoute() {
		return Route;
	}
	public void setRoute(String route) {
		Route = route;
	}

}
