package com.hibernate;

/**
 * RailwayStationsInCity generated by hbm2java
 */
public class RailwayStationsInCity implements java.io.Serializable {

	/*private RailwayStationsInCityId id;

	public RailwayStationsInCity() {
	}

	public RailwayStationsInCity(RailwayStationsInCityId id) {
		this.id = id;
	}

	public RailwayStationsInCityId getId() {
		return this.id;
	}

	public void setId(RailwayStationsInCityId id) {
		this.id = id;
	}*/

	
	
}
